# sur quel port le serveur démarre
server:
  port: 8080

# Les informations de connexion de la bd
spring:
  datasource:
    username: postgres
    password: 292424
    url: jdbc:postgresql://localhost:5432/l3miage
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: create-drop